#!/bin/sh

signer=$1
kt=$2

pubkey=/etc/ssh/ssh_host_${kt}_key.pub
cert=/etc/ssh/ssh_host_${kt}_cert.pub

if [ ! -e "$pubkey" ]; then
  echo "Invalid key type: $kt" >&2
  exit 1
fi

new_cert=$(mktemp)

# Nicked from OpenBSD's installer's .profile; print the public key
# every second (after a 0.2 second delay to connect).
set +m
exec 3<&1 4<&2 >/dev/null 2>&1
(
  exec >/dev/console
  sleep 0.2
  while perl -pe 's/$/\r/' <$pubkey; do sleep 1; done
) &
print_pid=$!
exec 1<&3 2<&4 3<&- 4<&-

trap 'kill $print_pid 2>/dev/null; rm -f $new_cert' EXIT

ssh "$signer" sign-request "$(hostname)" <$pubkey >$new_cert
_r=$?
if [ $_r != 0 ]; then
  echo Failed to obtain certificate >&2
  exit $_r
fi

cat $new_cert > "$cert"
